server:
  context-path: /api

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: 'jdbc:h2:file:~/test/valorprofs'
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: true

#  jackson:
#    date-format: org.codehaus.jackson.map.util.ISO8601DateFormat
